### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Hyakkimaru**
Juste une lettre manquante.

### CODE REVIEW

**Comment by xchopin** [comment]
Line 21: typo

**Comment by Hyakkimaru** [comment]
Of course you can, these tutorials are written for people who ignore everything about this "world", I give them my solution even if a lot of others possibilities are possible :)

**Comment by xchopin** [comment]
Ok my bad I thought it was a tutorial for coders, a kind of technical sheet

**Comment by Hyakkimaru** [comment]
Oh no, I'm sure the best coders won't need this !

**Comment by ldlac** [comment]
Belle initiative pour le tuto ;) !

**Pull request merged**
